name: tenang
description: Projek Akhir Praktikum Matakuliah Pemrograman Mobile

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  smooth_page_indicator: ^1.0.0+2
  flutter_bloc: ^6.1.3
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  carousel_slider: ^4.1.1
  expandable: ^5.0.1
  intl: ^0.17.0
  firebase_storage: ^10.2.18
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tenang.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
  - family: Poppins
    fonts: 
    - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf